"""Initial migration

Revision ID: abe7139ca849
Revises: 
Create Date: 2025-12-23 10:08:03.476440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe7139ca849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('track_artist', sa.String(), nullable=False),
    sa.Column('track_popularity', sa.Integer(), nullable=False),
    sa.Column('track_album_id', sa.String(), nullable=False),
    sa.Column('track_album_name', sa.String(), nullable=False),
    sa.Column('track_album_release_date', sa.String(), nullable=False),
    sa.Column('playlist_name', sa.String(), nullable=True),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.Column('playlist_genre', sa.String(), nullable=True),
    sa.Column('playlist_subgenre', sa.String(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('loudness', sa.Float(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('speechiness', sa.Float(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=False),
    sa.Column('instrumentalness', sa.Float(), nullable=False),
    sa.Column('liveness', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
